name: lcmap-tap
dependencies:
  - python=3.6.7
  - numpy=1.15.4
  - pandas=0.23.4
  - cytoolz=0.9.0.1
  - cython=0.29
  - pip:
      - PyYAML==3.13
      - PyQt==5.10.1
      - matplotlib==3.0.2
      - requests==2.21.0